### ISSUE TITLE
can support `v0.1.0` format, now it panic

### ISSUE THREAD

**Issue by songjiayang** [coreos/go-semver#29]
panic: strconv.ParseInt: parsing "v0": invalid syntax

goroutine 1 [running]:
github.com/coreos/go-semver/semver.Must(...)

**Comment by lucab** [comment]
This bug report is a bit terse, but I think it is a duplicate of https://github.com/coreos/go-semver/pull/28. Short summary is that the `v` prefix is not part of semver spec, thus it is rejected by this library.

**Comment by songjiayang** [comment]
@lucab thanks, just close it.
