### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by elgohr** [coreos/go-semver#41]
@bgilbert could you please publish a release, so that https://github.com/coreos/go-semver/commit/2a019005f501bd12992393992c5ed9d1fb27e889 will reach users?

**Comment by lucab** [comment]
I guess we should problably bump to https://github.com/go-yaml/yaml/releases/tag/v3.0.1 first.

**Comment by bgilbert** [comment]
`yaml` bump in https://github.com/coreos/go-semver/pull/43.

**Comment by bgilbert** [comment]
Tagged as [v0.3.1](https://github.com/coreos/go-semver/releases/tag/v0.3.1).
